# -*- coding: utf-8 -*-
"""ybi.foundation_Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AoJpijoT3bnXsBCnNGNRNXcK8fmmowtU

Servo Prediction

objective - Servo Prediction using Linear Regression
"""

#Importing Library
import pandas as pd

#importing data set
df= pd.read_csv("https://raw.githubusercontent.com/YBIFoundation/Dataset/main/Servo%20Mechanism.csv")

df.head()

df.replace({"Motor" : {"A":0 ,"B":1,"C":2,"D":3,"E":4}},inplace=True)

df.replace({"Screw" :{"A":0 ,"B":1,"C":2,"D":3,"E":4}},inplace=True)

df.info()

df.describe()

df.columns

Y=df['Class']

"""define target (Y) and features (X)"""

Y.shape

X=df[['Motor','Screw','Pgain','Vgain']]

X.shape

#Train test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,Y,train_size=0.7,random_state=2529)

#Select Model
from sklearn.linear_model import LinearRegression
lr= LinearRegression()

lr.fit( X_train, y_train)

lr.intercept_

lr.coef_

# Model Prediction
y_pred= lr.predict(X_test)

y_pred

# Accuracy
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test,y_pred)

